---

- hosts: all
  tasks:
    - name: Install Basic Packages
      become: yes
      become_user: root
      dnf:
        state: latest
        name: "{{ item }}"
      with_items:
        - vim
        - zsh
        - htop
        - rdiff-backup
        - curl
        - git
        - tree

    - name: Clone `oh-my-zsh` Repository
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh

    - name: Clone `dotfiles` Repository
      git:
        repo: https://github.com/fwilhe/dotfiles.git
        dest: ~/.dotfiles
      register: clone_dotfiles
    - name: Symlink Dotfiles
      shell: ~/.dotfiles/install
      when: clone_dotfiles.changed

    - name: Clone `bin` Repository
      git:
        repo: https://github.com/fwilhe/bin.git
        dest: ~/bin

    - name: Install OpenJDK
      become: yes
      become_user: root
      dnf:
        state: latest
        name: java-1.8.0-openjdk-devel

    - name: Create `~/code/github` Directory
      file:
        path: ~/code/github
        state: directory

    - name: Create `~/temp` Directory
      file:
        path: ~/temp
        state: directory

    - name: Create `~/no_backup` Directory
      file:
        path: ~/no_backup
        state: directory
