---

- hosts: all
  tasks:
    - name: Set Inotify Watches Limit
      become: yes
      copy:
        dest: /etc/sysctl.d/idea.conf
        content: fs.inotify.max_user_watches = 524288

    - name: Apply Inotify Watches Limit
      become: yes
      shell: sysctl -p --system

    - name: Install NPM (fedora)
      become: yes
      dnf:
        name: npm
      when: ansible_os_family == 'RedHat'

    - name: Install NPM (debian)
      become: yes
      apt:
        name: npm
      when: ansible_os_family == 'Debian'

    - name: Install tldr pages
      become: yes
      npm:
        name: tldr
        global: yes

  roles:
    - java
    - c
