---

  - name: Upgrade all Packages
    become: yes
    become_user: root
    dnf:
      state: latest
      name: "*"

  - name: Install Basic Packages
    become: yes
    become_user: root
    dnf:
      state: latest
      name: "{{ item }}"
    with_items:
      - vim
      - zsh
      - htop
      - mc
      - rdiff-backup
      - curl
      - git
      - tree
      - autojump
      - autojump-zsh
      - unzip
      - rubygem-asciidoctor
      - rubygem-asciidoctor-pdf
      - python3-httpie
      - the_silver_searcher
      - apg
      - jq
      - pandoc-static
    when: ansible_os_family == 'RedHat'

