---

  - name: Install Basic Packages
    become: yes
    become_user: root
    dnf:
      state: latest
      name: "{{ item }}"
    with_items:
      - autojump-zsh
      - rubygem-asciidoctor
      - rubygem-asciidoctor-pdf
    when: ansible_os_family == 'RedHat'
