---

  - name: Upgrade all Packages
    become: yes
    become_user: root
    dnf:
      state: latest
      name: "*"

  - name: Install Basic Packages
    become: yes
    become_user: root
    dnf:
      state: latest
      name: "{{ item }}"
    with_items:
      - vim
      - zsh
      - htop
      - rdiff-backup
      - curl
      - git
      - tree
      - autojump
      - autojump-zsh
      - unzip
    when: ansible_os_family == 'RedHat'
