---

  - name: Install Basic Packages
    become: yes
    become_user: root
    package:
      state: latest
      name: "{{ item }}"
    with_items:
      - vim
      - zsh
      - htop
      - rdiff-backup
      - curl
      - git
      - tree
      - autojump
      - unzip
    tags: basic

  - include: fedora.yml
    when: ansible_os_family == 'RedHat'
    tags: basic
