---

  - name: Upgrade all Packages
    become: yes
    become_user: root
    dnf:
      state: latest
      name: "*"
    when: ansible_os_family == 'RedHat'

  - name: Upgrade all Packages
    become: yes
    become_user: root
    apt:
      upgrade: dist
    when: ansible_os_family == 'Debian'

  - name: Install Basic Packages
    become: yes
    become_user: root
    dnf:
      state: latest
      name: "{{ item }}"
    with_items:
      - vim
      - zsh
      - htop
      - rdiff-backup
      - curl
      - git
      - tree
      - autojump
      - autojump-zsh
    when: ansible_os_family == 'RedHat'

  - name: Install Basic Packages
    become: yes
    become_user: root
    apt:
      state: latest
      name: "{{ item }}"
    with_items:
      - vim
      - zsh
      - htop
      - rdiff-backup
      - curl
      - git
      - tree
      - autojump
    when: ansible_os_family == 'Debian'
