---

- name: Ensure Group "docker" exists
  become: yes
  become_user: root
  group:
    name: docker
    state: present

- name: Add User to Group "docker"
  become: yes
  become_user: root
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Enable and Start Docker Daemon
  become: yes
  become_user: root
  service:
    name: docker
    enabled: yes
    state: started
