---
- name: Install Dependencies
  become: yes
  dnf:
    state: latest
    name: "{{ item }}"
  with_items:
    - ruby-devel
    - redhat-rpm-config
    - "@C Development Tools and Libraries"
    - zlib-devel
  when: ansible_os_family == 'RedHat'

- name: Install Backup
  become: yes
  gem:
    state: latest
    name: backup
    user_install: no
    include_doc: yes
