---

  - name: Install Development Packages
    become: yes
    become_user: root
    apt:
      state: latest
      name: "{{ item }}"
    with_items:
      - maven
      - gradle
      - ant
    when: ansible_os_family == 'Debian'

  - name: Set `JAVA_HOME`
    become: yes
    lineinfile:
      dest: /etc/environment
      line: JAVA_HOME="/usr/lib/jvm/default-java"
