---

  - name: Ensure `~/software` directory exists
    file:
      path: ~/software
      state: directory

  - name: Clone `fwilhe/bin` Repository
    git:
      repo: https://github.com/fwilhe/bin.git
      dest: ~/software/fwilhe-bin

  - name: Install `fwilhe-bin` for all users
    become: yes
    make:
      chdir: "{{ ansible_env.HOME }}/software/fwilhe-bin"
      target: install
