---

  - name: Install Development Packages
    become: yes
    become_user: root
    dnf:
      state: latest
      name: "{{ item }}"
    with_items:
      - java-1.8.0-openjdk
      - maven
      - gradle
      - ant
    when: ansible_os_family == 'RedHat'

