---

- name: Install Docker
  become: yes
  dnf:
    state: latest
    name: docker
  when: ansible_os_family == 'RedHat'

- name: Install Docker
  become: yes
  apt:
    state: latest
    name: docker.io
  when: ansible_os_family == 'Debian'

- name: Ensure Group "docker" exists
  become: yes
  become_user: root
  group:
    name: docker
    state: present

- name: Add User to Group "docker"
  become: yes
  become_user: root
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Enable and Start Docker Daemon
  become: yes
  become_user: root
  service:
    name: docker
    enabled: yes
    state: started
