---

- hosts: all
  tasks:
    - name: Install Basic Desktop Packages
      become: yes
      become_user: root
      dnf:
        state: latest
        name: "{{ item }}"
      with_items:
        - thunderbird
        - keepassx
      when: ansible_os_family == 'RedHat'

    - command: gsettings set org.gnome.desktop.input-sources xkb-options "['compose:caps']"

    - command: gsettings set org.gnome.desktop.wm.keybindings switch-input-source "[]"

    - command: gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "[]"

    - command: gsettings set org.gnome.Terminal.Legacy.Settings menu-accelerator-enabled "false"

